[workspace]
exclude = [
  "arm-targets",
  "examples/versatileab",
  "examples/mps3-an536",
  "examples/mps3-an536-smp",
]
members = [
  "aarch32-cpu",
  "aarch32-rt",
  "aarch32-rt-macros",
]
resolver = "2"
